// OVERALL APP
export const APP_READY = 'APP_READY';
export const APP_STATUS_CHANGE = 'APP_STATUS_CHANGE';
export const FEATURE_SWITCH = 'FEATURE_SWITCH';
// DATA
export const REQUEST_DATA_FAKE = 'REQUEST_DATA_FAKE';
export const RECEIVE_DATA_FAKE_SUCCESS = 'RECEIVE_DATA_FAKE_SUCCESS';
export const RECEIVE_DATA_FAKE_FAIL = 'RECEIVE_DATA_FAKE_FAIL';
// GRID
export const GRID_STATUS_CHANGE = 'GRID_STATUS_CHANGE';
export const GRID_SORT = 'GRID_SORT';
export const GRID_FILTERS_CHANGE = 'GRID_FILTERS_CHANGE';
export const GRID_FILTERS_CLEAR = 'GRID_FILTERS_CLEAR';
export const GRID_REQUEST_SAVE = 'GRID_REQUEST_SAVE';
export const GRID_RECEIVE_SAVE_SUCCESS = 'GRID_RECEIVE_SAVE_SUCCESS';
export const GRID_RECEIVE_SAVE_FAIL = 'GRID_RECEIVE_SAVE_FAIL';
export const GRID_ROWS_UPDATE = 'GRID_ROWS_UPDATE';
// PAGING
export const PAGING_CHANGE_LIMIT = 'PAGING_CHANGE_LIMIT';
// BULK SELECTION
export const BULK_DISPLAY = 'BULK_DISPLAY';
export const BULK_CURRENT_PAGE_REQUEST = 'BULKSELECTION_CURRENT_PAGE_REQUEST';
export const BULK_CURRENT_PAGE_RECEIVED_FAIL =
  'BULKSELECTION_CURRENT_PAGE_RECEIVED_FAIL';
export const BULK_CURRENT_PAGE_RECEIVED_SUCCESS =
  'BULKSELECTION_CURRENT_PAGE_RECEIVED_SUCCESS';
export const BULK_PAGE_UPDATE_START = 'BULK_PAGE_UPDATE_START';
export const BULK_PAGE_UPDATE_COMPLETE = 'BULK_PAGE_UPDATE_COMPLETE';
